spring:
  datasource:
    url: jdbc:postgresql://localhost/projectmanager
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
  jpa:
    generate-ddl: true
  freemarker:
    expose-request-attributes: true
    suffix: .ftl
